services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge
